export const TYPES = {
	APPLICATION: Symbol.for('APPLICATION'),
	LOGGER: Symbol.for('LOGGER'),
	AUTHCONTROLLER: Symbol.for('AUTHCONTROLLER'),
	AUTHSERVICE: Symbol.for('AUTHSERVICE'),
	PASSWORDSERVICE: Symbol.for('PASSWORDSERVICE'),
	USERSSERVICE: Symbol.for('USERSSERVICE'),
	TOKENSERVICE: Symbol.for('TOKENSERVICE'),
	CONFIGSERVICE: Symbol.for('CONFIGSERVICE'),
	EXCEPTIONFILTER: Symbol.for('EXCEPTIONFILTER'),
	PRISMASERVICE: Symbol.for('PRISMASERVICE'),
	USERSREPOSITORY: Symbol.for('USERSREPOSITORY'),
};
